#+AUTHOR: Hyper

* My Dotfiles

Welcome to my personal dotfiles repository!

While the core of my system configuration is declaratively managed using [[https://nixos.org/][NixOS]], this repository houses the configurations I tend to tweak and iterate on more frequently.

Previously, I explored managing these user-level configurations directly within my NixOS setup, including attempts at symlinking. However, these earlier approaches proved less reliable than desired for frequently modified files

** My Environmetn 

Here are the tools that I think work best for a linux-based dev environment.

- *Emacs*: My primary editor, terminal, file browser and more powered by vim-keybinds.
- *Hyprland*: BSPWM was my home, but Hyprland gets pretty close.
- *Zsh*: My preffered shell (Though [[https://www.nushell.sh/][Nushell]] would eventually be nice)
- *Ghostty*: If I need an application that vshell can't run.

** Usage

[TODO]

 free to browse, borrow, and adapt any parts of this configuration that you find useful for your own setup!.
