exec-once=hyprctl setcursor Qogir-cursors 24
exec-once=ags
exec-once=swayosd-server

$terminal = alacritty
$menu = wofi --show drun

# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that
env = WLR_NO_HARDWARE_CURSORS,1
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

monitor=DP-3, 1920x1080, 0x0, 1
monitor=HDMI-A-1, 1920x1080, 1920x0, 1

# Offset workspaces by 10 to give room; ags renames them anyway
workspace = 1, monitor:DP-3, persistent:true, default:true
workspace = 11, monitor:HDMI-A-1, persistent:true, default:true

input {
    kb_layout = us
    follow_mouse = 2
    accel_profile = flat
    sensitivity = 0
}

general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle

    allow_tearing = false
}

decoration {
    rounding = 0
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = no
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = yes 
    preserve_split = yes
    force_split = 2
    no_gaps_when_only = 1
}

misc {
    force_default_wallpaper = -1 
}

windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$

$mainMod = SUPER



bind = $mainMod, Return, exec, $terminal
bind = $mainMod, C, killactive, 
bind = $mainMod, D, togglefloating, 
bind = $mainMod, F, fullscreen, 0 
bind = $mainMod, M, fullscreen, 1
bind = $mainMod, space, exec, $menu
bind = $mainMod, P, pseudo,
bind = ,Print, exec, grimblast --freeze copy area


bind = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume +5
bind = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume -5
bind = ,XF86AudioMute, exec, $soundCue && swayosd-client --output-volume mute-toggle
bind = ,Num_Lock, exec, swayosd-client --num-lock && $soundCue
bind = ,Caps_Lock, exec, swayosd-client --caps-lock && $soundCue

bind = $mainMod, l, movefocus, r
bind = $mainMod, h, movefocus, l
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
