source = ~/.config/hypr/execs.conf

monitor=DP-2,2560x1440@144,auto-right,1
monitor=DP-3,2560x1440@144,auto-left,1

plugin {
    hyprsplit {
      num_workspaces = 5
      persistent_workspaces = 1
    }
}

general{
    gaps_in = 5
    gaps_out = 10
    border_size = 1
    col.active_border = rgba(bdadeabf)
    col.inactive_border = rgba(4e4c67bf)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 1
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

dwindle {
    preserve_split = true
    force_split = 2
}

misc {
    disable_hyprland_logo = false
}

input {
    numlock_by_default = true
    repeat_delay = 400
    accel_profile = flat
    follow_mouse = 2
}

source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowRules.conf
