(setq treesit-language-source-alist
      '((bash "https://github.com/tree-sitter/tree-sitter-bash")
        (c "https://github.com/tree-sitter/tree-sitter-c")
        (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
        (css "https://github.com/tree-sitter/tree-sitter-css")
        (glsl "https://github.com/tree-sitter-grammars/tree-sitter-glsl")
        (go "https://github.com/tree-sitter/tree-sitter-go")
        (gpg-config "https://github.com/tree-sitter-grammars/tree-sitter-gpg-config")
        (haskell "https://github.com/tree-sitter-grammars/tree-sitter-haskell")
        (hlsl "https://github.com/tree-sitter-grammars/tree-sitter-hlsl")
        (html "https://github.com/tree-sitter/tree-sitter-html")
        (hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")
        (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
        (json "https://github.com/tree-sitter/tree-sitter-json")
        (kotlin "https://github.com/tree-sitter-grammars/tree-sitter-kotlin")
        (make "https://github.com/tree-sitter-grammars/tree-sitter-make")
        (markdown "https://github.com/ikatyang/tree-sitter-markdown")
        (python "https://github.com/tree-sitter/tree-sitter-python")
        (rust "https://github.com/tree-sitter/tree-sitter-rust")
        (scss "https://github.com/tree-sitter-grammars/tree-sitter-scss")
        (slint "https://github.com/slint-ui/tree-sitter-slint")
        (ssh-config "https://github.com/tree-sitter-grammars/tree-sitter-ssh-config")
        (svelte "https://github.com/tree-sitter-grammars/tree-sitter-svelte")
        (toml "https://github.com/tree-sitter-grammars/tree-sitter-toml")
        (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
        (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
        (wgsl "https://github.com/tree-sitter-grammars/tree-sitter-wgsl-bevy")
        (yuck "https://github.com/tree-sitter-grammars/tree-sitter-yuck")
        (zig "https://github.com/tree-sitter-grammars/tree-sitter-zig")))

(setq treesit-load-name-override-list
      '((gpg-config "libtree-sitter-gpg-config" "tree_sitter_gpg")
        (wgsl "libtree-sitter-wgsl" "tree_sitter_wgsl_bevy")))

(defun treesit-install-all-grammars ()
  (interactive)
  (dolist (lang treesit-language-source-alist)
    (treesit-install-language-grammar (car lang))))

(defun treesit-install-missing-grammars ()
  (interactive)
  (dolist (lang treesit-language-source-alist)
    (unless (treesit-language-available-p (car lang))
      (treesit-install-language-grammar (car lang)))))

(define-derived-mode slint-ts-mode prog-mode "Slint"
  :group 'slint
  (when (treesit-ready-p 'slint)
    (treesit-parser-create 'slint)
    (setq-local treesit-simple-indent-rules
                '((slint
                   ((parent-is "source_file") column-0 0)
                   ((node-is "}") parent-bol 0)
                   ((node-is "]") parent-bol 0)
                   ((parent-is "component") parent-bol 2)
                   ((parent-is "element") parent-bol 2)
                   ((parent-is "callback") parent-bol 2)
                   ((parent-is "property") parent-bol 2)
                   (no-node parent-bol 2))))
    (setq-local indent-line-function 'treesit-indent)))

(mapc (lambda (pair)
        (add-to-list 'auto-mode-alist pair))
      '(("\\.c\\'" . c-ts-mode)
        ("\\.cpp\\'" . c++-ts-mode)
        ("\\.css\\'" . css-ts-mode)
        ("\\.frag\\'" . glsl-ts-mode)
        ("\\.glsl\\'" . glsl-ts-mode)
        ("\\.go\\'" . go-ts-mode)
        ("\\.h\\'" . c-or-c++-ts-mode)
        ("\\.hlsl\\'" . hlsl-ts-mode)
        ("\\.hs\\'" . haskell-ts-mode)
        ("\\.html\\'" . html-ts-mode)
        ("\\.js\\'" . js-ts-mode)
        ("\\.json\\'" . json-ts-mode)
        ("\\.kt\\'" . kotlin-ts-mode)
        ("\\.kts\\'" . kotlin-ts-mode)
        ("\\.md\\'" . markdown-ts-mode)
        ("\\.mjs\\'" . js-ts-mode)
        ("\\.mk\\'" . makefile-ts-mode)
        ("\\.py\\'" . python-ts-mode)
        ("\\.rs\\'" . rust-ts-mode)
        ("\\.scss\\'" . scss-ts-mode)
        ("\\.sh\\'" . bash-ts-mode)
        ("\\.slint\\'" . slint-ts-mode)
        ("\\.svelte\\'" . svelte-ts-mode)
        ("\\.toml\\'" . toml-ts-mode)
        ("\\.ts\\'" . typescript-ts-mode)
        ("\\.tsx\\'" . tsx-ts-mode)
        ("\\.vert\\'" . glsl-ts-mode)
        ("\\.wgsl\\'" . wgsl-ts-mode)
        ("\\.yuck\\'" . yuck-ts-mode)
        ("\\.zig\\'" . zig-ts-mode)
        ("/\\.gnupg/.*\\.conf\\'" . gpg-config-ts-mode)
        ("/\\.ssh/config\\'" . ssh-config-ts-mode)
        ("Makefile\\'" . makefile-ts-mode)
        ("hyprland\\.conf\\'" . hyprlang-ts-mode)))
