(setq treesit-language-source-alist
      '((bash "https://github.com/tree-sitter/tree-sitter-bash")
        (c "https://github.com/tree-sitter/tree-sitter-c")
        (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
        (c-sharp "https://github.com/tree-sitter/tree-sitter-c-sharp")
        (css "https://github.com/tree-sitter/tree-sitter-css")
        (glsl "https://github.com/tree-sitter-grammars/tree-sitter-glsl")
        (go "https://github.com/tree-sitter/tree-sitter-go")
        (gpg-config "https://github.com/tree-sitter-grammars/tree-sitter-gpg-config")
        (haskell "https://github.com/tree-sitter-grammars/tree-sitter-haskell")
        (hlsl "https://github.com/tree-sitter-grammars/tree-sitter-hlsl")
        (html "https://github.com/tree-sitter/tree-sitter-html")
        (hyprlang "https://github.com/WhySoBad/tree-sitter-hyprlang/" "color-declarations")
        (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
        (json "https://github.com/tree-sitter/tree-sitter-json")
        (kotlin "https://github.com/tree-sitter-grammars/tree-sitter-kotlin")
        (make "https://github.com/tree-sitter-grammars/tree-sitter-make")
        (markdown "https://github.com/ikatyang/tree-sitter-markdown")
        (python "https://github.com/tree-sitter/tree-sitter-python")
        (rust "https://github.com/tree-sitter/tree-sitter-rust")
        (scss "https://github.com/tree-sitter-grammars/tree-sitter-scss")
        (slint "https://github.com/slint-ui/tree-sitter-slint")
        (ssh-config "https://github.com/tree-sitter-grammars/tree-sitter-ssh-config")
        (svelte "https://github.com/tree-sitter-grammars/tree-sitter-svelte")
        (toml "https://github.com/tree-sitter-grammars/tree-sitter-toml")
        (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
        (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
        (wgsl "https://github.com/tree-sitter-grammars/tree-sitter-wgsl-bevy")
        (yuck "https://github.com/tree-sitter-grammars/tree-sitter-yuck")
        (zig "https://github.com/tree-sitter-grammars/tree-sitter-zig")))

(setq treesit-load-name-override-list
      '((gpg-config "libtree-sitter-gpg-config" "tree_sitter_gpg")
        (wgsl "libtree-sitter-wgsl" "tree_sitter_wgsl_bevy")))

(defun treesit-install-all-grammars ()
  (interactive)
  (dolist (lang treesit-language-source-alist)
    (treesit-install-language-grammar (car lang))))

(defun treesit-install-missing-grammars ()
  (interactive)
  (dolist (lang treesit-language-source-alist)
    (unless (treesit-language-available-p (car lang))
      (treesit-install-language-grammar (car lang)))))


(use-package fasm-mode :mode ("\\.asm\\'" . fasm-mode))
(use-package glsl-mode)
(use-package haskell-mode)
(use-package hyprlang-ts-mode
  :mode ("/hypr/.*\\.conf\\'"))
(use-package kotlin-mode)
(use-package markdown-mode)
(use-package rust-mode
  :init
  (setq rust-mode-treesitter-derive t))
(use-package svelte-mode)
(use-package wgsl-mode)
(use-package web-mode)
(use-package yuck-mode)
(use-package zig-mode)

(use-package slint-mode
  :straight (:host github :repo "nilclass/slint-mode"))
(define-derived-mode slint-ts-mode slint-mode "Slint TS"
  :group 'slint
  (when (treesit-ready-p 'slint)
    (treesit-parser-create 'slint)
    (setq-local treesit-simple-indent-rules
                '((slint
                   ((parent-is "source_file") column-0 0)
                   ((node-is "}") parent-bol 0)
                   ((node-is "]") parent-bol 0)
                   ((parent-is "component") parent-bol 2)
                   ((parent-is "element") parent-bol 2)
                   ((parent-is "callback") parent-bol 2)
                   ((parent-is "property") parent-bol 2)
                   (no-node parent-bol 2))))
    (setq-local indent-line-function 'treesit-indent)
    (treesit-major-mode-setup)))

(defun compile-dotnet-run ()
  (interactive)
  (compile "dotnet run"))

(setq major-mode-remap-alist
      '((c-mode              . c-ts-mode)
        (c++-mode            . c++-ts-mode)
        (c-or-c++-mode       . c-or-c++-ts-mode)
        (csharp-mode         . csharp-ts-mode)
        (css-mode            . css-ts-mode)
        (go-mode             . go-ts-mode)
        (haskell-mode        . haskell-ts-mode)
        (html-mode           . html-ts-mode)
        (js-mode             . js-ts-mode)
        (js-json-mode        . json-ts-mode)
        (kotlin-mode         . kotlin-ts-mode)
        (makefile-mode       . makefile-ts-mode)
        (makefile-gmake-mode . makefile-ts-mode)
        (markdown-mode       . markdown-ts-mode)
        (python-mode         . python-ts-mode)
        (rust-mode           . rust-ts-mode)
        (sh-mode             . bash-ts-mode)
        (toml-mode           . toml-ts-mode)
        (typescript-mode     . typescript-ts-mode)
        (conf-toml-mode      . toml-ts-mode)))

(mapc (lambda (pair)
        (add-to-list 'auto-mode-alist pair))
      '(("\\.cs\\'" . csharp-ts-mode)
        ("\\.frag\\'" . glsl-ts-mode)
        ("\\.glsl\\'" . glsl-ts-mode)
        ("\\.hlsl\\'" . hlsl-ts-mode)
        ("\\.slint\\'" . slint-ts-mode)
        ("\\.svelte\\'" . svelte-ts-mode)
        ("\\.vert\\'" . glsl-ts-mode)
        ("\\.wgsl\\'" . wgsl-ts-mode)
        ("\\.yuck\\'" . yuck-ts-mode)
        ("\\.zig\\'" . zig-ts-mode)
        ("/\\.gnupg/.*\\.conf\\'" . gpg-config-ts-mode)
        ("/\\.ssh/config\\'" . ssh-config-ts-mode)))
