#################################
#         Font Config           #
#################################

font_family JetBrains Mono
disable_ligatures never
font_size 13

# "Nerd Fonts - Pomicons"
symbol_map  U+E000-U+E00D Symbols Nerd Font

# "Nerd Fonts - Powerline"
symbol_map U+e0a0-U+e0a2,U+e0b0-U+e0b3 Symbols Nerd Font

# "Nerd Fonts - Powerline Extra"
symbol_map U+e0a3-U+e0a3,U+e0b4-U+e0c8,U+e0cc-U+e0d2,U+e0d4-U+e0d4 Symbols Nerd Font

# "Nerd Fonts - Symbols original"
symbol_map U+e5fa-U+e62b Symbols Nerd Font

# "Nerd Fonts - Devicons"
symbol_map U+e700-U+e7c5 Symbols Nerd Font

# "Nerd Fonts - Font awesome"
symbol_map U+f000-U+f2e0 Symbols Nerd Font

# "Nerd Fonts - Font awesome extension"
symbol_map U+e200-U+e2a9 Symbols Nerd Font

# "Nerd Fonts - Octicons"
symbol_map U+f400-U+f4a8,U+2665-U+2665,U+26A1-U+26A1,U+f27c-U+f27c Symbols Nerd Font

# "Nerd Fonts - Font Linux"
symbol_map U+F300-U+F313 Symbols Nerd Font

#  Nerd Fonts - Font Power Symbols"
symbol_map U+23fb-U+23fe,U+2b58-U+2b58 Symbols Nerd Font

#  "Nerd Fonts - Material Design Icons"
symbol_map U+f500-U+fd46 Symbols Nerd Font

# "Nerd Fonts - Weather Icons"
symbol_map U+e300-U+e3eb Symbols Nerd Font

# Misc Code Point Fixes
symbol_map U+21B5,U+25B8,U+2605,U+2630,U+2632,U+2714,U+E0A3,U+E615,U+E62B Symbols Nerd Font


#################################
#           Cursor              #
#################################

cursor_shape beam
shell_integration no-cursor
cursor_blink_interval 500
cursor_stop_blinking_after 0
copy_on_select yes
strip_trailing_spaces always


#################################
#         Scrollback            #
#################################

scrollback_lines 10000
scrollback_fill_enlarged_window no


#################################
#             Misc              #
#################################

confirm_os_window_close 0
placement_strategy center
sync_to_monitor yes
enable_audio_bell no
visual_bell_duration 0.0
url_style straight

#################################
#            Theme              #
#         Tokyo-Night           #
#################################

background_opacity .85

foreground #A0A8CD
background #11121D

# Black
color0 #06080A 
color8 #06080A 

# Red
color1 #EE6D85 
color9 #EE6D85 

# Green
color2  #95C561
color10 #95C561

# Yellow
color3   #D7A65F
color11  #D7A65F

# Blue
color4  #7199EE
color12  #7199EE

# Magenta
color5  #A485DD
color13  #A485DD

# Cyan
color6  #7dcfff
color14 #7dcfff

# White
color7  #787c99
color15  #787c99

# Cursor
cursor none

# Selection highlight
selection_foreground none
selection_background none

# The color for highlighting URLs on mouse-over
url_color #9ece6a

# Tab bar
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_min_tabs 2
tab_bar_style fade
tab_fade 1
active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold
inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold
tab_bar_background #101014
